# Wrangler configuration file
# This file provides the same configuration as wrangler.jsonc but in TOML format
# for better compatibility with deployment platforms

name = "perigon-mcp-server"
main = "worker/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[[migrations]]
new_sqlite_classes = ["MyMCP"]
tag = "v1"

[[migrations]]
tag = "v2"
[[migrations.renamed_classes]]
from = "MyMCP"
to = "PerigonMCP"

[durable_objects]
bindings = [
  { class_name = "PerigonMCP", name = "MCP_OBJECT" }
]

[assets]
directory = "./dist/"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/v1/*"]

[observability]
enabled = true

upload_source_maps = true

[vars]
MCP_URL = "http://localhost:5173"

[env.production]
name = "mcp-perigon-production"
account_id = "8de3c02e1e299ec1561c53e44fb76ad7"

[[env.production.routes]]
pattern = "mcp.perigon.io"
custom_domain = true

[env.production.durable_objects]
bindings = [
  { class_name = "PerigonMCP", name = "MCP_OBJECT" }
]

[env.production.vars]
MCP_URL = "https://mcp.perigon.io"