export interface AuthIntrospectionResponse {
  scopes: Scopes[];
}

export enum Scopes {
  VECTOR_SEARCH_NEWS = "VECTOR_SEARCH_NEWS",
  JOURNALISTS = "JOURNALISTS",
  PEOPLE = "PEOPLE",
  HISTORICAL_NEWS = "HISTORICAL_NEWS",
  TOPICS = "TOPICS",
  ENTITIES = "ENTITIES",
  SENTIMENTS = "SENTIMENTS",
  COMPANIES = "COMPANIES",
  REAL_TIME_NEWS = "REAL_TIME_NEWS",
  LABELS = "LABELS",
  LOCATIONS = "LOCATIONS",
  REPRINTS = "REPRINTS",
  SOURCES = "SOURCES",
  CATEGORIES = "CATEGORIES",
  PAYWALL = "PAYWALL",
  CLUSTERS = "CLUSTERS",
  KEYWORDS = "KEYWORDS",
}
