name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
        with:
          bun-version: 1.2.16

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build
        env:
          CLOUDFLARE_ENV: production
          VITE_TURNSTILE_SITE_KEY: "0x4AAAAAABihR9-NN72ssFjf"
          VITE_USE_TURNSTILE: "true"

      - name: Deploy
        run: bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ENV: production
